source('funcs.R')
source('generator.R')

# par <- seq(0, 2, length.out = 5)
# generate(par1 = par, par2 = 1, distr = rnorm, n = 5, exact = TRUE, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 5, length.out = 5), distr = rnorm, n = 5, exact = TRUE, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rnorm, n = 5, exact = TRUE, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rnorm, n = 5, exact = TRUE, folder = 'mean2var')

# par <- seq(0, 4, length.out = 5)
# generate(par1 = par, par2 = 1, distr = rcauchy, n = 5, exact = TRUE, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 9, length.out = 5), distr = rcauchy, n = 5, exact = TRUE, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rcauchy, n = 5, exact = TRUE, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rcauchy, n = 5, exact = TRUE, folder = 'mean2var')

# par <- seq(0, 2, length.out = 5)
# generate(par1 = seq(0, 3, length.out = 5), par2 = 1, distr = rlaplace, n = 5, exact = TRUE, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 13, length.out = 5), distr = rlaplace, n = 5, exact = TRUE, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rlaplace, n = 5, exact = TRUE, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rlaplace, n = 5, exact = TRUE, folder = 'mean2var')

# par <- seq(0, 10, length.out = 5)
# generate(par1 = par, par2 = 1, distr = rlevy, n = 5, exact = TRUE, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 25, length.out = 5), distr = rlevy, n = 5, exact = TRUE, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rlevy, n = 5, exact = TRUE, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rlevy, n = 5, exact = TRUE, folder = 'mean2var')

# par <- seq(0, 8, length.out = 5)
# generate(par1 = par, par2 = 1, distr = rlogcauchy, n = 5, exact = TRUE, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 25, length.out = 5), distr = rlogcauchy, n = 5, exact = TRUE, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rlogcauchy, n = 5, exact = TRUE, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rlogcauchy, n = 5, exact = TRUE, folder = 'mean2var')

# par <- seq(0, 1, length.out = 5)
# generate(par1 = seq(0, 0.8, length.out = 5), par2 = 1, distr = rnorm, n = 50, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 3, length.out = 5), distr = rnorm, n = 50, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rnorm, n = 50, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rnorm, n = 50, folder = 'mean2var')

# par <- seq(0, 2, length.out = 5)
# generate(par1 = par, par2 = 1, distr = rcauchy, n = 50, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 5, length.out = 5), distr = rcauchy, n = 50, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rcauchy, n = 50, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rcauchy, n = 50, folder = 'mean2var')

# par <- seq(0, 0.5, length.out = 5)
# generate(par1 = seq(0, 1, length.out = 5), par2 = 1, distr = rlaplace, n = 50, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 3, length.out = 5), distr = rlaplace, n = 50, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rlaplace, n = 50, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rlaplace, n = 50, folder = 'mean2var')

# par <- seq(0, 1, length.out = 5)
# generate(par1 = par, par2 = 1, distr = rlevy, n = 50, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 3, length.out = 5), distr = rlevy, n = 50, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rlevy, n = 50, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rlevy, n = 50, folder = 'mean2var')

# par <- seq(0, 1, length.out = 5)
# generate(par1 = par, par2 = 1, distr = rlogcauchy, n = 50, folder = 'mean')
# generate(par1 = 0, par2 = seq(1, 5, length.out = 5), distr = rlogcauchy, n = 50, folder = 'var')
# generate(par1 = par, par2 = 1+par, distr = rlogcauchy, n = 50, folder = 'mean1var')
# generate(par1 = par, par2 = 1+2*par, distr = rlogcauchy, n = 50, folder = 'mean2var')
